on:
    pull_request:
      branches: [ master ]
      paths-ignore:
        - 'docs/**'
        - 'README.md'

concurrency:
    group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
    cancel-in-progress: true
    
jobs:

    build:
        uses: ./.github/workflows/build.yml

    test:
        uses: ./.github/workflows/test.yml

    mpi:
        uses: ./.github/workflows/mpi.yml

    mcfost:
        uses: ./.github/workflows/mcfost.yml
        
    growth:
        uses: ./.github/workflows/growth.yml

    krome:
        uses: ./.github/workflows/krome.yml